// Formations: each slot has a required position-group ("slot" key matching players.json),
// a display label, and x/y percentage coordinates on the pitch (0,0 = top-left, attacking goal at top).
const FORMATIONS = {
  "4-4-2": {
    label: "4-4-2",
    slots: [
      { id: "gk",   slot: "GK",  label: "GK",  x: 50, y: 92 },
      { id: "lb",   slot: "LB",  label: "LB",  x: 14, y: 74 },
      { id: "cb1",  slot: "CB",  label: "CB",  x: 36, y: 78 },
      { id: "cb2",  slot: "CB",  label: "CB",  x: 64, y: 78 },
      { id: "rb",   slot: "RB",  label: "RB",  x: 86, y: 74 },
      { id: "lm",   slot: "LM",  label: "LM",  x: 14, y: 46 },
      { id: "cm1",  slot: "CM",  label: "CM",  x: 36, y: 50 },
      { id: "cm2",  slot: "CM",  label: "CM",  x: 64, y: 50 },
      { id: "rm",   slot: "RM",  label: "RM",  x: 86, y: 46 },
      { id: "st1",  slot: "ST",  label: "ST",  x: 38, y: 16 },
      { id: "st2",  slot: "ST",  label: "ST",  x: 62, y: 16 },
    ],
  },
  "4-3-3": {
    label: "4-3-3",
    slots: [
      { id: "gk",   slot: "GK",  label: "GK",  x: 50, y: 92 },
      { id: "lb",   slot: "LB",  label: "LB",  x: 14, y: 74 },
      { id: "cb1",  slot: "CB",  label: "CB",  x: 36, y: 78 },
      { id: "cb2",  slot: "CB",  label: "CB",  x: 64, y: 78 },
      { id: "rb",   slot: "RB",  label: "RB",  x: 86, y: 74 },
      { id: "cdm",  slot: "CDM", label: "CDM", x: 50, y: 60 },
      { id: "cm1",  slot: "CM",  label: "CM",  x: 28, y: 48 },
      { id: "cm2",  slot: "CM",  label: "CM",  x: 72, y: 48 },
      { id: "lw",   slot: "LW",  label: "LW",  x: 14, y: 20 },
      { id: "st",   slot: "ST",  label: "ST",  x: 50, y: 12 },
      { id: "rw",   slot: "RW",  label: "RW",  x: 86, y: 20 },
    ],
  },
  "4-2-3-1": {
    label: "4-2-3-1",
    slots: [
      { id: "gk",   slot: "GK",  label: "GK",  x: 50, y: 92 },
      { id: "lb",   slot: "LB",  label: "LB",  x: 14, y: 74 },
      { id: "cb1",  slot: "CB",  label: "CB",  x: 36, y: 78 },
      { id: "cb2",  slot: "CB",  label: "CB",  x: 64, y: 78 },
      { id: "rb",   slot: "RB",  label: "RB",  x: 86, y: 74 },
      { id: "cdm1", slot: "CDM", label: "CDM", x: 36, y: 58 },
      { id: "cdm2", slot: "CDM", label: "CDM", x: 64, y: 58 },
      { id: "lam",  slot: "LW",  label: "LAM", x: 16, y: 34 },
      { id: "cam",  slot: "CAM", label: "CAM", x: 50, y: 30 },
      { id: "ram",  slot: "RW",  label: "RAM", x: 84, y: 34 },
      { id: "st",   slot: "ST",  label: "ST",  x: 50, y: 12 },
    ],
  },
  "3-5-2": {
    label: "3-5-2",
    slots: [
      { id: "gk",   slot: "GK",  label: "GK",  x: 50, y: 92 },
      { id: "cb1",  slot: "CB",  label: "CB",  x: 26, y: 78 },
      { id: "cb2",  slot: "CB",  label: "CB",  x: 50, y: 80 },
      { id: "cb3",  slot: "CB",  label: "CB",  x: 74, y: 78 },
      { id: "lwb",  slot: "LWB", label: "LWB", x: 10, y: 52 },
      { id: "cm1",  slot: "CM",  label: "CM",  x: 34, y: 52 },
      { id: "cdm",  slot: "CDM", label: "CDM", x: 50, y: 58 },
      { id: "cm2",  slot: "CM",  label: "CM",  x: 66, y: 52 },
      { id: "rwb",  slot: "RWB", label: "RWB", x: 90, y: 52 },
      { id: "st1",  slot: "ST",  label: "ST",  x: 38, y: 16 },
      { id: "st2",  slot: "ST",  label: "ST",  x: 62, y: 16 },
    ],
  },
  "5-3-2": {
    label: "5-3-2",
    slots: [
      { id: "gk",   slot: "GK",  label: "GK",  x: 50, y: 92 },
      { id: "lwb",  slot: "LWB", label: "LWB", x: 8,  y: 72 },
      { id: "cb1",  slot: "CB",  label: "CB",  x: 28, y: 80 },
      { id: "cb2",  slot: "CB",  label: "CB",  x: 50, y: 82 },
      { id: "cb3",  slot: "CB",  label: "CB",  x: 72, y: 80 },
      { id: "rwb",  slot: "RWB", label: "RWB", x: 92, y: 72 },
      { id: "cm1",  slot: "CM",  label: "CM",  x: 30, y: 50 },
      { id: "cdm",  slot: "CDM", label: "CDM", x: 50, y: 54 },
      { id: "cm2",  slot: "CM",  label: "CM",  x: 70, y: 50 },
      { id: "st1",  slot: "ST",  label: "ST",  x: 38, y: 16 },
      { id: "st2",  slot: "ST",  label: "ST",  x: 62, y: 16 },
    ],
  },
};
